export const theme = {
  colors: {
    background: "var(--theme-background)",
    backgroundAccent: "var(--theme-background-accent)",
    surface: "var(--theme-surface)",
    surfaceAlt: "var(--theme-surface-alt)",
    surfaceSoft: "var(--theme-surface-soft)",
    border: "rgba(168, 125, 52, 0.18)",
    text: "var(--theme-text)",
    textSecondary: "var(--theme-text-secondary)",
    textMuted: "var(--theme-text-muted)",
    accent: "var(--theme-accent)",
    accentSoft: "var(--theme-accent-soft)",
    accentLight: "var(--theme-accent-light)",
    positive: "var(--theme-positive)",
    help: "var(--theme-help)",
    warning: "var(--theme-warning)",
    danger: "var(--theme-danger)",
    button: "var(--theme-button)",
    buttonText: "var(--theme-button-text)",
    buttonBorder: "rgba(168, 125, 52, 0.24)",
    neutral: "var(--theme-neutral)",
  },
  gradients: {
    primary: "linear-gradient(135deg, var(--theme-accent-soft), var(--theme-accent))",
    muted: "linear-gradient(135deg, rgba(140,94,45,0.08), rgba(248,237,215,0.2))",
  },
  shadow: "0 24px 60px rgba(113, 84, 41, 0.12)",
  radius: "14px",
};
